### ISSUE TITLE
Nullable Foreign key

### ISSUE THREAD

**Issue by maitredede** [uadmin/uadmin#102]
Hello,

How should I declare my model to have a recursive optionnal foreign key ?

For example :

```golang
type Someone struct {
	uadmin.Model

	Mother   *Someone
	MotherID *uint

	Father   *Someone
	FatherID *uint
}
```
The actual ui behavior shows 2 columns : one for target struct, one for "pointer value of id field". And when trying to insert using dropdowns, the otherID field is not filled.

**Comment by maitredede** [comment]
I am trying to make a new test function, for this struct :

```golang
type Parentality struct {
	Model
	OptionalParent    *Parentality
	OptionalParentID  *uint
	MandatoryParent   *Parentality
	MandatoryParentID uint
}
```
Correct me if I am wrong, but I think there are problems :
- The `MandatoryParent` field should be marked as `required` since its `ID` field is a non nullable type (gorm will make it non nullable in database). Keeping the struct field as pointer is fine, to distinguish if data has been preloaded or not.
- The `OptionalParent` field is not parsed correctly : both field and `ID` are present in schema. An error is shown in log about "not an integer based number", but it is a nullable number. I have seen in code that number validation is limited to plain number types, but pointer types should be usable too, and `sql.Null*` types also.

**Comment by Gaurav-Gosain** [comment]
Hi @maitredede, I'm still a newbie at both go and uAdmin so please ignore this if im completely off topic or misunderstood the question, correct me if i'm wrong but from what I understand from your question you want the ability to have an optional Parent (as in preload should not load any data), how I would currently tackle such a situation would be by keeping the `OptionalParentID` as a `uint` instead of `*uint` and would set it to the value of `0` for the `OptionalParent` to reference null. I'm not sure if that answers your questions or helps you in any way but will put it out there anyways 😅

**Comment by TwistedHardware** [comment]
Thanks for the suggestion.

The problem is we didn't break the public API since 0.0.1 which was not even open source yet. To do that we have to change `uadmin.Model.ID` from `uint` to either `*uint` or some Nullable unit. But that would break part of the public API (`model.ID`). THe way we do it now is to check if the `ID` is zero which is the best thing we can do without breaking the API.
