### ISSUE TITLE
I got an error when installing

### ISSUE THREAD

**Issue by 52lemon** [uadmin/uadmin#2]
`
C:\Users\dell>go get github.com/uadmin/uadmin
# cd .; git clone https://github.com/uadmin/uadmin E:\GOPATH\src\github.com\uadm
in\uadmin
Cloning into 'E:\GOPATH\src\github.com\uadmin\uadmin'...
fatal: early EOF
fatal: the remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
package github.com/uadmin/uadmin: exit status 128
`

**Comment by uadmin** [comment]
I'm not really sure why is that. I just tried to replicate the error and could not.
I ran this on both Windows and Linux and it worked on both.

Anyway your installation command is also incomplete. you should use:
`go get -u github.com/uadmin/uadmin/...`

the `/...` part is important because it installs the command-line tool for uadmin to be able to run `uadmin prepare`. Otherwise you will have to install the command tool manually:

```
E:\GOPATH\src\github.com\uadmin\uadmin\cmd\uadmin> go installl
```

Maybe it was a network error. Can please try to install it again. If it fails please report:
- OS + OS Version
- Golang version

This will help me replicate your environment.

Thanks for reporting.

**Comment by 52lemon** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\dell>go version
go version go1.10.1 windows/amd64

C:\Users\dell>git --version
git version 2.19.1.windows.1

C:\Users\dell>

OS--windows 7 sp1

**Comment by uadmin** [comment]
I think your problem is slow Internet connection as per this:
https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining

Based on that question and answer, A work around for installing uadmin on a slow connection would be:

```
C:\Users\dell>cd E:\GOPATH\src\github.com
E:\GOPATH\src\github.com>mkdir uadmin
E:\GOPATH\src\github.com>cd uadmin
git clone http://github.com/uadmin/uadmin --depth 1
cd uadmin
git fetch --unshallow
cd E:\GOPATH\src\github.com\uadmin\uadmin\cmd\uadmin
go install
```

can you please try that and let me know if it works for you.

**NOTE**: For future reference: change `E:\GOPATH\src\github.com` with your actual GOPATH
