### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by snyff** [uadmin/uadmin#55]
Hi,

Just wondering what is the best way to report a security issue?

Best,
Louis

**Comment by dxlvgcw** [comment]
If this is something that you have to discuss it privately, we can suggest the developers to have support email in uadmin.

**Comment by snyff** [comment]
Whatever works best for you. Just let me know.

**Comment by Spotlight64** [comment]
As of now, the only way is to report an issue in Github. I'll consider @dxlvgcw 's suggestion to implement an inquiry email for uAdmin that will be discussed by ourselves. 

To report a security issue, you have to include the requested information listed below (as much as you can provide) to help us better understand the nature and scope of the possible issue.
* URL
* Type of issue (SQL injection, Man-in-the-middle attack, etc.)
* Version of uAdmin that you have installed
* Issue description
* Impact of the issue
* Source code / screenshots
* Other information (e.g. caused by third-party tool, browser security, etc.)

**Comment by uadmin** [comment]
Can you please send the details to support@uadmin.io

**Comment by snyff** [comment]
Sent
