### ISSUE TITLE
[  ERROR ]   DB error in Filter(set). record not found

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#63]
Hi, I search for items like this
uadmin.Filter(&auctions, "number_of_collection = ?", key)

they are not found, but it's writing to log the message
```
[  ERROR ]   DB error in Filter(set). record not found
```

how to tell it that it totally fine if there are no items found, I just checking? How to handle this error?

**Comment by Spotlight64** [comment]
Hello, use ErrorHandleFunc to handle the error.
https://uadmin-docs.readthedocs.io/en/latest/api/print_functions.html#uadmin-errorhandlefunc

**Comment by MarErm27** [comment]
> 
> 
> Hello, use ErrorHandleFunc to handle the error.
> https://uadmin-docs.readthedocs.io/en/latest/api/print_functions.html#uadmin-errorhandlefunc

I handle the error like this:
```
	uadmin.ErrorHandleFunc = func(level int, msg string, stack string) {
		if level >= uadmin.ERROR {
			if msg == "DB error in Filter(set). record not found\n"{
				fmt.Println("ooooooops")
			}
			//fmt.Println("ERROR MESSAGE:\n" + msg + "\n")
			//fmt.Println("STACK:\n" + stack + "\n")
		}
	}
```

but I still got this in logs:
```
[  ERROR ]   DB error in Filter(set). record not found
ooooooops
```

How to make it silent?

**Comment by MarErm27** [comment]
@Spotlight64 do Uadmin support HSQL? I think instead of find I need to make a Query with Count()*

**Comment by Spotlight64** [comment]
Assign the value of Reporting Level to 5 in the Settings so that the error message will hide in the console.

![Untitled](https://user-images.githubusercontent.com/49872771/87862981-b8b7a600-c988-11ea-8a53-5e67c59b1eb1.png)

For now, Uadmin only supports SQLite and MySQL. You can use Count function: https://uadmin-docs.readthedocs.io/en/latest/api/fetching_records.html#uadmin-count

**Comment by dxlvgcw** [comment]
@Spotlight64 It will hide the error message everywhere which is not good because it will create more problems when you expand the coverage of your application. You will never see why your application does not work.
@MarErm27 If you want to hide the error message for that specific action, it seems there is no solution yet but like @Spotlight64 mentioned, check whether the record is available.

**Comment by Spotlight64** [comment]
@dxlvgcw You are right. Since you are always active and supportive to solve issues here, I'm willing to invite you as a collaborator of uAdmin. Is that okay to you?

**Comment by dxlvgcw** [comment]
Of course! It is an honor for me to work with you and your team.

**Comment by Spotlight64** [comment]
Thank you so much. Let's wait for the owner's approval. He is the one who assigned user roles.
