### ISSUE TITLE
Slow down. You are going too fast!

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#77]
Hello!
Here is a check in main_handler.go
```
	if !CheckRateLimit(r) {
		w.Write([]byte("Slow down. You are going too fast!"))
		return
	}
```
Here is the CheckRateLimit function
```
// CheckRateLimit checks if the request has remaining quota or not. If it returns false,
// the IP in the request has exceeded their quota
func CheckRateLimit(r *http.Request) bool {
	rateLimitLock.Lock()
	ip, _, _ := net.SplitHostPort(r.RemoteAddr)
	now := time.Now().Unix() * RateLimit
	if val, ok := rateLimitMap[ip]; ok {
		if (val + RateLimitBurst) < now {
			rateLimitMap[ip] = now - RateLimitBurst
		}
	} else {
		rateLimitMap[ip] = now - RateLimit
	}

	rateLimitMap[ip]++
	rateLimitLock.Unlock()
	return rateLimitMap[ip] <= now
}
```

The problem is I have many users with same IP and their IP almost instantly reaches the quota. They literally can't log in. I was wondering if there are a way to turn off this feature or to change it's behaviour. Thank you!

**Comment by MarErm27** [comment]
@TwistedHardware Hello! I was wondering if you might be able to help

The problem is I have many users with same IP and their IP almost instantly reaches the quota. They literally can't log in. I was wondering if there are a way to turn off this feature or to change it's behaviour. Thank you!

**Comment by Spotlight64** [comment]
Hello! You have to adjust the RateLimit and RateLimitBurst value to something higher in the Settings page on uadmin dashboard. Sample below

![Untitled](https://user-images.githubusercontent.com/49872771/126936151-c7fc48d6-bb35-44a9-bef9-265cb0713c8a.png)

Alternative solution if you are unable to access the Settings page in the UI is to adjust the value in code. Example:
'''
// Assign the Rate Limit value to 100
setting := uadmin.Setting{}
uadmin.Get(&setting, "code = ?", "uAdmin.RateLimit")
setting.ParseFormValue([]string{"100"})
setting.Save()
'''

If the alternative solution still doesn't work, maybe you can try to print out the value of the Allowed IP/Blocked IP in the Settings model through the code. It might be due to the invalid format.

**Comment by MarErm27** [comment]
Thank you, @Spotlight64 , I've changed the settings and don't see this problem anymore.
